### ISSUE TITLE
Во время замены продукта можно выйти из инвентаря, не получив этот продукт

### ISSUE THREAD

**Issue by Tr1xxter** [Teel-Software/HybridHarvest#14]

**Comment by debebantur** [comment]
А не истёк ли срок действия. Насколько я понял, всё норм. В противном случае, укажи, при каких конкретно действиях происходит баг.

**Comment by debebantur** [comment]
Да, всё работает.

**Comment by debebantur** [comment]
Деньги не работают

**Comment by debebantur** [comment]
Теперь нельзя
