### ISSUE TITLE
Хаос с добавлением, заменой и выбором семян

### ISSUE THREAD

**Issue by JustSock** [Teel-Software/HybridHarvest#27]
При добавлении семян из магазина даже при наличие свободного места откроется окно замены пакетов.
При замене пакета семян выбирается предыдущий пакет вместо выбранного.
При выборе семян для посадки выбирается предыдущий пакет/нажатие не пакет регистрируется вообще.

**Comment by debebantur** [comment]
Тестеры перестали жаловаться
