### ISSUE TITLE
Проблемы с энергией

### ISSUE THREAD

**Issue by debebantur** [Teel-Software/HybridHarvest#8]
При нажатии на энергию активируется префаб панели, а сама она не  появляется.

**Comment by Tr1xxter** [comment]
Контекст <br>

![image](https://user-images.githubusercontent.com/74663481/141060263-aa6f1bf6-0352-4d8d-9089-d7de8cc0bed9.png)

**Comment by Teelirium** [comment]
Вроде исправлено
