### ISSUE TITLE
Редкость не обновляется

### ISSUE THREAD

**Issue by Tr1xxter** [Teel-Software/HybridHarvest#9]
При добавлении объекта в инвентарь, текстура остаётся дефолтной, даже если предмет редкий. Спрайт пакета меняется только при перезаходе на сцену

**Comment by debebantur** [comment]
А каким способом ты добавляешь объект?

**Comment by Tr1xxter** [comment]
> А каким способом ты добавляешь объект?

Через магазин <br>
![image](https://user-images.githubusercontent.com/74663481/141056652-839e54d6-1a74-4721-ae39-3846be9cdaed.png)

**Comment by Tr1xxter** [comment]
Исправил
